// lib/database.types.ts
// Auto-generated by: npm run db:types
// Run after setting up Supabase to get full type safety

export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[];

export interface Database {
  public: {
    Tables: {
      profiles: {
        Row: { id: string; whop_user_id: string|null; display_name: string|null; plan: string; created_at: string; updated_at: string; };
        Insert: { id: string; whop_user_id?: string|null; display_name?: string|null; plan?: string; };
        Update: { whop_user_id?: string|null; display_name?: string|null; plan?: string; };
      };
      desktop_states: {
        Row: { id: string; user_id: string; icon_positions: Json; open_windows: Json; settings: Json; updated_at: string; };
        Insert: { user_id: string; icon_positions?: Json; open_windows?: Json; settings?: Json; };
        Update: { icon_positions?: Json; open_windows?: Json; settings?: Json; updated_at?: string; };
      };
      hot_signals: {
        Row: { id: string; user_id: string|null; ticker: string; score: number; dp_notional: number|null; flow_type: string|null; fired_at: string; };
        Insert: { user_id?: string|null; ticker: string; score: number; dp_notional?: number|null; flow_type?: string|null; };
        Update: Record<string, never>;
      };
      journal_entries: {
        Row: { id: string; user_id: string; content: string; updated_at: string; };
        Insert: { user_id: string; content?: string; };
        Update: { content?: string; updated_at?: string; };
      };
      trades: {
        Row: { id: string; user_id: string; ticker: string; direction: string; entry_price: number; exit_price: number|null; size: number; pnl: number|null; opened_at: string; status: string; };
        Insert: { user_id: string; ticker: string; direction: string; entry_price: number; size: number; };
        Update: { exit_price?: number; pnl?: number; status?: string; closed_at?: string; };
      };
      watchlists: {
        Row: { id: string; user_id: string; name: string; tickers: string[]; created_at: string; };
        Insert: { user_id: string; name?: string; tickers?: string[]; };
        Update: { tickers?: string[]; name?: string; };
      };
      gamma_signals: {
        Row: { id: string; ticker: string; signal: string; regime: string; confidence: number|null; timeframe: string|null; fired_at: string; };
        Insert: { ticker: string; signal: string; regime: string; confidence?: number|null; timeframe?: string|null; };
        Update: Record<string, never>;
      };
      news_cache: {
        Row: { id: string; headline: string; category: string|null; url: string|null; is_breaking: boolean; published_at: string|null; };
        Insert: { headline: string; category?: string|null; url?: string|null; };
        Update: Record<string, never>;
      };
    };
  };
}
